name: Discord Notify

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "📢 새로운 PR 업데이트\nPR: '${{ github.event.pull_request.title }}'\n작성자: '${{ github.actor }}'\n링크: '${{ github.event.pull_request.html_url }}'"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
